### ISSUE TITLE
Missing data for 2020 Penticton 

### ISSUE THREAD

**Issue by aseagram** [bcgov/envair#11]
There was a temporary station operating in Penticton in 2020. There should be at least PM2.5 data, but this seems to be missing when using the `importBC_data()` function. The data may be missing from the ftp. See example below.

```
library(envair)
library(openair)
library(tidyr)

station <- "Penticton Industrial Place"
years <- 2019:2021

pm25 <- importBC_data("PM25", years = years)

stationPM25 <- pm25 %>%
  filter(STATION_NAME == station) %>%
  select(-c(LONGITUDE, LATITUDE, ROUNDED_VALUE)) %>%
  rename(PM25 = RAW_VALUE,
         date = DATE_PST)

summaryPlot(stationPM25, na.len = 0)
```

**Comment by jeromerobles** [comment]
I can't seem to duplicate the issue. try reloading the package and let me know if it is still a problem
