### ISSUE TITLE
importBC_data error for aqhi

### ISSUE THREAD

**Issue by DonnaHaga** [bcgov/envair#17]
R Version 4.3.1. envair version 0.4.0.100

Is is possible to access aqhi data using importBC_data? I don't see the value showed when I tried...

`envair::importBC_data(parameter_or_station="aqhi",years=2023)`

![envair](https://github.com/bcgov/envair/assets/24443567/d3595dff-a648-4bc4-98c5-8957c5663624)

**Comment by jeromerobles** [comment]
updated to report AQHI data
