### ISSUE TITLE
Golden Helipad NA's

### ISSUE THREAD

**Issue by DonnaHaga** [bcgov/envair#19]
R Version 4.3.1 envair version 0.4.0.100.

For Golden Helipad there are some entries with `INSTRUMENT` as `NA` along with many other columns.

```
# import data: hourly PM2.5 for the last 10 years
data<-envair::importBC_data(parameter_or_station = "pm25",
                            years=2014:2023,
                            use_openairformat = FALSE
                            )

# there are entries for instrument == NA in golden's data
data %>%
  dplyr::filter(STATION_NAME=="Golden Helipad") %>%
  dplyr::filter(is.na(INSTRUMENT)) 
```

![goldenNAs](https://github.com/bcgov/envair/assets/24443567/7d0da83a-df14-4533-908e-eb8b0ad6dd2b)

**Comment by jeromerobles** [comment]
data<-envair::importBC_data(parameter_or_station = "pm25",
                            years=2014:2023,
                            use_openairformat = FALSE
)

data %>%
  dplyr::filter(station_name=="Golden Helipad") %>%
  dplyr::filter(is.na(instrument)) %>%
  nrow()

result is 0 rows.

**Comment by DonnaHaga** [comment]
Thanks @jeromerobles :). I tried again and also got zero rows this time. Weird. 

How come the data you imported automatically get converted to lower case names and mine stay in caps? I used `remotes::install_github("bcgov/envair")` to make sure i have the most recent version. am i missing something?

**Comment by jeromerobles** [comment]
New update to keep the all caps column name as default.

**Comment by DonnaHaga** [comment]
all good to close now
