### ISSUE TITLE
INSTRUMENT NA's for Port Edward Sunset Drive 2022

### ISSUE THREAD

**Issue by DonnaHaga** [bcgov/envair#23]
`Port Edward Sunset Drive` has a subset of data with `NA` in the `INSTRUMENT` field that has all `NA` in the `RAW_VALUE` fields. I presume this data can be deleted from the database.

```
portEd<-envair::importBC_data(parameter_or_station = "Port Edward Sunset Drive",
                              years=2022,
                              use_openairformat = FALSE)

portEd %>%
  dplyr::group_by(PARAMETER,INSTRUMENT) %>%
  dplyr::summarise(sum(!is.na(RAW_VALUE)),
                   sum(is.na(RAW_VALUE)),
                   n())
```

**Comment by jeromerobles** [comment]
NA in instrument fixed in envair 0.4.0.300. Padding or filling of data now excludes instruments that have not reported data
